polar_bear_links_list = ["https://static.boredpanda.com/blog/wp-content/uploads/2016/02/cute-baby-polar-bear-day-photography-201__880.jpg",
                    # "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1aY3UT1GUOwUjBcPH-2zZa_d1Cr2OicOkkiAhTA4d6pza33oG-DW8Szy897JNoQ1hXZ0&usqp=CAU",
                    # "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9PaHtRB-1_ETj_l1IG7enXZl1ps2Qu9htSA&usqp=CAU",
                    # "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSU0KGRmYcSzVx1cm_QVY4QXwgK8778bfQ0aBhj-0tArB1GkQPOnc0PLFqO6yVffUvbSF8&usqp=CAU",
                    # "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0z2x6irDvXByDIJKXwQk4aJQWbswmtpCCZ71rLLevLtEFE-4YtaiVRupyMtH_W56e7oE&usqp=CAU",
                    # "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSY5naCF60ebNGi-oCBNsNdc_9vp2L9wvFLUA&usqp=CAU",
                    "https://s.abcnews.com/images/International/polar-bears-03-ht-llr-220227_1645998492735_hpMain_1x1_608.jpg",
                    "https://i.ytimg.com/vi/kD2RxEGkCIg/maxresdefault.jpg",
                    "https://www.gannett-cdn.com/media/USATODAY/WiresImages/2013/03/20/27d3302e6e559b092c0f6a7067009e5a-16_9.jpg",
                    "https://i2-prod.mirror.co.uk/incoming/article5738207.ece/ALTERNATES/s615b/Young-polar-bear-tries-to-climb-in-boat.jpg",
                    "https://i2-prod.irishmirror.ie/incoming/article5738880.ece/ALTERNATES/s615b/Young-polar-bear-tries-to-climb-in-boat.jpg",
                    "https://www.discover-the-world.com/app/uploads/2018/07/polar-bear-close-up-1150x863-c-default.jpg",
                    "https://www.sciencekids.co.nz/images/pictures/animals/polarbearcubs.jpg",                    
                    "https://i.ytimg.com/vi/-Kfl3385O44/maxresdefault.jpg",
                    "https://i.ytimg.com/vi/McFVUmb1mao/maxresdefault.jpg",
                    "https://cdn-images.vetstreet.com/2f/ff4020541111e19be6005056ad4734/file/sikusnow630aa021012.jpg",
                    "https://thumbs.dreamstime.com/b/playful-young-polar-bears-northern-canada-two-cute-playfully-interacting-snowy-ice-hudson-bay-near-churchill-manitoba-205952366.jpg",
                    ]

